; --------------------------------------------------------------------------------- 
; Corhoma - Informática e Ingeniería
; Configuración del programa test integracon Signafile / AD    
;  v1.02- 20260317 
; ------------------------------------------------------------------------------------

[node_idpas_cfg]
;;  -------------------------------------------------------------------------------- 
;; [Platform & Security]
;;  -------------------------------------------------------------------------------- 

;; SEC_MODE  --> [1 - ADBB only] [2 - enviroment ] 
SEC_MODE = 1

;; A/D black box path 
CUBB_PATH = "C:/Externos/Corhoma/Servidores/DSER"

;;  -------------------------------------------------------------------------------- 
;; [AD instance]
;;  -------------------------------------------------------------------------------- 

; fqdns name or ip  del AD service
;LDAP_SERVER = 127.0.0.1
LDAP_SERVER = "172.16.100.29"

; ADLDS server port
;LDAP_PORT = 60636
LDAP_PORT = 60389

; Conexion encriptada ( S ) o ( N * )
LDAPS = "N"

; path certificados
CERT_PATH = C:\externos\corhoma\ldapcerts\CACERT.pem

; --------- relativo al dominio
BASE_DN=CN=CRHADLDS,DC=SIGNAFILE

 
; --------- usuario por defecto para buscar en el LDAP
USUARIO =  USRADMIN

; --------  Path archivo de log
LOG_FPATH = "sgf_node_idpas_test.log" 

;;  -------------------------------------------------------------------------------- 
;;  EOF   
;;  --------------------------------------------------------------------------------
