; --------------------------------------------------------------------------------- 
; Corhoma - Informática e Ingeniería
; Configuración del programa test integracon Signafile / AD    
;  v1.06- 20260331 
; ------------------------------------------------------------------------------------

[node_idpas_cfg]
;;  -------------------------------------------------------------------------------- 
;; [Platform & Security]
;;  -------------------------------------------------------------------------------- 

;; SEC_MODE  --> [1 - ADBB only] [2 - enviroment ] 
SEC_MODE = 1

;; A/D black box path 
CUBB_PATH = "C:/Externos/Corhoma/Servidores/DSER"
;;CUBB_PATH = "./adblackbox"

;;  -------------------------------------------------------------------------------- 
;; [AD instance]
;;  -------------------------------------------------------------------------------- 

; fqdns name or ip  del AD service
;LDAP_SERVER = 127.0.0.1
;;LDAP_SERVER = "172.16.100.29"
LDAP_SERVER = "172.16.100.53"


; ADLDS server port
;LDAP_PORT = 60636
;;LDAP_PORT = 60389
LDAP_PORT = 389


; Conexion encriptada ( S ) o ( N * )
LDAPS = "N"

; path certificados
CERT_PATH = C:\externos\corhoma\ldapcerts\CACERT.pem

; --------- relativo al dominio
;;BASE_DN=CN=CRHADLDS,DC=SIGNAFILE
;;BASE_DN=OU=Usuarios,DC=crhm-cloud-labo,DC=dev
;;BASE_DN=DC=crhm-cloud-labo,DC=dev
BASE_DN = crhm-cloud-labo.dev
 


; --------  Path archivo de log
LOG_FPATH = "sgf_node_idpas_test.log" 

;;  -------------------------------------------------------------------------------- 
;;  EOF   
;;  --------------------------------------------------------------------------------
